spring:
  profiles:
    active: redis-embedded
    
server:
  port: 8888

rest:
  user: restadmin
  pass: restadmin
  
cdmi:
  data:
    baseDirectory: /tmp/cdmi
  qos:
    backend:
      type: dummy_filesystem
---
spring:
  profiles: filesystem
cdmi:
  data:
    objectIdPrefix: .cdmi_
---
spring:
  profiles: redis
  redis:
    port: 6379
